### PR TITLE
Adding support for refunds.

### PR DESCRIPTION
**Pull request by ndeet**

### CODE REVIEW

**Comment by ndeet** [comment]
Can be merged as soon as [this PR ](https://github.com/btcpayserver/btcpayserver/pull/4539) is released to a BTCPay Server version.

**Comment by pavlenex** [comment]
@ndeet Do you have any blockers into adding refunds into Woo?

**Comment by ndeet** [comment]
Yes, it is me doing the needed documentation as it will require new api key permissions and for users upgrading it means they need to create a new api key for that. Was a bit distracted with other work but I work to finish this today and tomorrow so I can do that major release and link to the corresponding instructions. Also need to do a final test round and update the WooCommerce installation docs.

**Comment by ndeet** [comment]
added docs pr here yesterday https://github.com/btcpayserver/btcpayserver-doc/pull/1238 

as soon as merged I can merge this a and do a major release

**Pull request merged**
